-- MySQL Script generated by MySQL Workbench
-- Wed Jul 20 08:42:13 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema modelo
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `modelo` ;

-- -----------------------------------------------------
-- Schema modelo
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `modelo` DEFAULT CHARACTER SET utf8 ;
USE `modelo` ;

-- -----------------------------------------------------
-- Table `modelo`.`aluno`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `modelo`.`aluno` ;

CREATE TABLE IF NOT EXISTS `modelo`.`aluno` (
  `id` INT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `celular` VARCHAR(13) NOT NULL,
  `email` VARCHAR(60) NOT NULL,
  `github_usuario` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `modelo`.`prova`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `modelo`.`prova` ;

CREATE TABLE IF NOT EXISTS `modelo`.`prova` (
  `id` INT NOT NULL,
  `disciplina` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `modelo`.`pergunta`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `modelo`.`pergunta` ;

CREATE TABLE IF NOT EXISTS `modelo`.`pergunta` (
  `id` INT NOT NULL,
  `pergunta` VARCHAR(45) NOT NULL,
  `prova_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_pergunta_prova1_idx` (`prova_id` ASC) VISIBLE,
  CONSTRAINT `fk_pergunta_prova1`
    FOREIGN KEY (`prova_id`)
    REFERENCES `modelo`.`prova` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `modelo`.`resposta`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `modelo`.`resposta` ;

CREATE TABLE IF NOT EXISTS `modelo`.`resposta` (
  `id` INT NOT NULL,
  `resposta` VARCHAR(45) NOT NULL,
  `pergunta_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_resposta_pergunta1_idx` (`pergunta_id` ASC) VISIBLE,
  CONSTRAINT `fk_resposta_pergunta1`
    FOREIGN KEY (`pergunta_id`)
    REFERENCES `modelo`.`pergunta` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `modelo`.`aluno_prova`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `modelo`.`aluno_prova` ;

CREATE TABLE IF NOT EXISTS `modelo`.`aluno_prova` (
  `aluno_id` INT NOT NULL,
  `prova_id` INT NOT NULL,
  PRIMARY KEY (`aluno_id`, `prova_id`),
  INDEX `fk_aluno_has_prova_prova1_idx` (`prova_id` ASC) VISIBLE,
  INDEX `fk_aluno_has_prova_aluno_idx` (`aluno_id` ASC) VISIBLE,
  CONSTRAINT `fk_aluno_has_prova_aluno`
    FOREIGN KEY (`aluno_id`)
    REFERENCES `modelo`.`aluno` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_aluno_has_prova_prova1`
    FOREIGN KEY (`prova_id`)
    REFERENCES `modelo`.`prova` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
