-- MySQL Script generated by MySQL Workbench
-- Thu Jul 21 09:11:06 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema db_agregacao
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `db_agregacao` ;

-- -----------------------------------------------------
-- Schema db_agregacao
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_agregacao` DEFAULT CHARACTER SET utf8 ;
USE `db_agregacao` ;

-- -----------------------------------------------------
-- Table `db_agregacao`.`produto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_agregacao`.`produto` ;

CREATE TABLE IF NOT EXISTS `db_agregacao`.`produto` (
  `Cod_Prod` INT NOT NULL,
  `Cod_Clas` INT NOT NULL,
  `Tipo_Prod` VARCHAR(45) NOT NULL,
  `Nome_Prod` VARCHAR(45) NOT NULL,
  `Qtd_Prod` INT NOT NULL,
  PRIMARY KEY (`Cod_Prod`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_agregacao`.`classe`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_agregacao`.`classe` ;

CREATE TABLE IF NOT EXISTS `db_agregacao`.`classe` (
  `Cod_Clas` INT NOT NULL,
  `Nome_Clas` VARCHAR(45) NOT NULL,
  `Cod_Prod` INT NOT NULL,
  PRIMARY KEY (`Cod_Clas`, `Cod_Prod`),
  INDEX `fk_classe_produto_idx` (`Cod_Prod` ASC) VISIBLE,
  CONSTRAINT `fk_classe_produto`
    FOREIGN KEY (`Cod_Prod`)
    REFERENCES `db_agregacao`.`produto` (`Cod_Prod`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
